### PR TITLE
Left array join support

### PR DESCRIPTION
**Pull request by suvorovis**

### CODE REVIEW

**Comment by suvorovis** [comment]
Hi! Could you please merge this and release? I am using this part of code in my project. Thank you!

**Comment by evsign** [comment]
Hi. Add please methods for other join types and possibility to pass the type in `arrayJoin` method. Also it would be great if you could write info about these new methods in the readme. Thanks for pr!

**Comment by suvorovis** [comment]
Thanks for your reply! I've added info in the readme. Regarding the other join types - only left join is allowed (https://clickhouse.tech/docs/en/sql-reference/statements/select/array-join/). Therefore, I think it will be safer for use if I don't add the type parameter to `arrayJoin` method.

**Comment by evsign** [comment]
Merged and tagged. Thanks!:)

**Pull request merged**
