### PR TITLE
add joinOn with multiple possibility

### PR DESCRIPTION
**Pull request by ogbofjnr**
Old interfaces not changed, added joinOn() on builder that supports join conditions and multiple joins.

### CODE REVIEW

**Comment by ogbofjnr** [comment]
There are linting issues, some lines that I didn't change according to git, but CI server mark it as changed.

**Comment by chelsEg** [comment]
> There are linting issues, some lines that I didn't change according to git, but CI server mark it as changed.

You need something like this git pull https://github.com/the-tinderbox/ClickhouseBuilder.git master.
And then resolve conficts.

**Comment by ogbofjnr** [comment]
Just like that, after 6 months of silence. Not sure I want to contribute any more with such an attitude.
At a time it was no conflicts, but the issue with inconsistent linting of project.
Do you actually want to merge it? Otherwise I see no point in solving conflicts now.

**Comment by chelsEg** [comment]
> Just like that, after 6 months of silence. Not sure I want to contribute any more with such an attitude.
> At a time it was no conflicts, but the issue with inconsistent linting of project.
> Do you actually want to merge it? Otherwise I see no point in solving conflicts now.

I'm don't work on this project.
I'm user who used this project 😃 
I think it's very interesting issue for other users.

**Pull request closed without merging**
